CONFIG_LOG_DEFAULT_LEVEL=4
#CONFIG_SHELL=n

#CONFIG_BOOTLOADER_MCUBOOT=y
#CONFIG_MCUBOOT_SIGNATURE_KEY_FILE="/home/ana/arduino-puppy/bootloader/mcuboot/root-ec-p256.pem"
#CONFIG_MCUBOOT_IMGTOOL_SIGN_VERSION="0.0.1"
#CONFIG_MCUBOOT_EXTRA_IMGTOOL_ARGS="-L0x1c010000"
#CONFIG_MCUBOOT_BOOTLOADER_MODE_RAM_LOAD=y