CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_MCUBOOT_BOOTLOADER_MODE_SINGLE_APP_RAM_LOAD=y
CONFIG_MCUBOOT_GENERATE_UNSIGNED_IMAGE=y

CONFIG_COUNTER=y
CONFIG_PINCTRL=n
CONFIG_LOG_MODE_MINIMAL=y
CONFIG_SPI_NOR_SFDP_RUNTIME=y
