CONFIG_MCUBOOT_LOG_LEVEL_DBG=y
CONFIG_LOG_DEFAULT_LEVEL=4

#CONFIG_BOOT_IMAGE_EXECUTABLE_RAM_START=0x1c020000
#CONFIG_BOOT_IMAGE_EXECUTABLE_RAM_SIZE=393216

CONFIG_I2C=n
CONFIG_PM=n
CONFIG_LOG_MODE_MINIMAL=n
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=n
CONFIG_MCUBOOT_SERIAL=y
CONFIG_BOOT_SERIAL_UART=y
CONFIG_BOOT_SERIAL_NO_APPLICATION=y
CONFIG_MCUBOOT_INDICATION_LED=y
#CONFIG_BOOT_SERIAL_WAIT_FOR_DFU=y
#CONFIG_BOOT_SERIAL_WAIT_FOR_DFU_TIMEOUT=5000

CONFIG_OUTPUT_DISASSEMBLY=y
CONFIG_OUTPUT_SYMBOLS=y